### ISSUE TITLE
`runtime: shiny` in Rmarkdown doesn't know how to handle htmlDependency()

### ISSUE THREAD

**Issue by daattali** [rstudio/htmltools#375]
If an `htmltools::htmlDependency()` gets added to the UI of a regular shiny app, shiny knows how to treat it as a dependency and add the scripts/css files to the head.

If it gets added to a shiny-powered Rmarkdown, it gets converted to text. 

Example:

The following shiny app adds the fontawesome dependencies, and therefore the icon shows up

```r
library(shiny)

ui <- fluidPage(
  fontawesome::fa_html_dependency(),
  tags$i(class = "fas fa-pencil")
)

server <- function(input, output, session) {}

shinyApp(ui, server)
```

The following Rmarkdown treats the dependency as text

````r
---
runtime: shiny
---

```{r}
fontawesome::fa_html_dependency()
tags$i(class = "fas fa-pencil")
```
````

The rmarkdown version does work if I wrap the dependency in an empty `attachDependencies()`:

```r
htmltools::attachDependencies(HTML(''), fontawesome::fa_html_dependency())
```

This is technically not a bug because the documentation of `htmlDependency()` does say that these objects are meant to go inside `attachDependencies()`, but in practice because it works in regular shiny apps I would expect it to also work in Rmd.

**Comment by cderv** [comment]
> The root issue is that there isn't a knit_print.html_dependency method, which could be (or should be) provided by htmltools.

👋 R Markdown team here 😉 

@gadenbuie had it right. Yes this is how the information about dependency is passed to **knitr** usually. This is explained in the vignette about custom print method : https://cran.r-project.org/web/packages/knitr/vignettes/knit_print.html#metadata

So dependencies needs to be wrapped into `tagList()` because `htmltools::knit_print.shiny.tag.list` takes care of doing what is need to pass the `meta` to **knitr** using `knitr::asis_output()`

Those type of things are supposed to be handled in associated package and not in **knitr** directly. **htmltools** seems the right place for that.
