### ISSUE TITLE
Include tags$svg, tags$g, tags$path, etc.

### ISSUE THREAD

**Issue by jcheng5** [rstudio/htmltools#84]
Also probably should check with latest relevant specs to make sure we're not missing any new tags.

cc @Stophface @timelyportfolio

**Comment by wch** [comment]
Do we want to include the tags for elements inside the svg?

**Comment by jcheng5** [comment]
Yep. I'll amend the title.

**Comment by banbh** [comment]
Note that tags in htmltools do not convert "." in "-" (in contrast to `css()`). I.e., `css(a.b=1)` is `a-b:1;` but `p(a.b=1)` is `<p a.b="1"></p>`. This may be relevant because many SVG attributes have hyphens (see https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute) as opposed to HTML, where hardly any do.

Might it make sense for all tags to convert "." to "-" (in attributes)? Or perhaps to do so optionally, so that SVG tags could be made to do so?

**Comment by Bogaso** [comment]
Is there any update on this request?

**Comment by schloerke** [comment]
@banbh You are allowed to send in `-`'ed names.

```r
htmltools::p(`a-b` = 1)
#> <p a-b="1"></p>
htmltools::p("a-b" = 1)
#> <p a-b="1"></p>
```
